# Generated by Django 4.1 on 2024-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="id",
        ),
        migrations.AddField(
            model_name="book",
            name="book_number",
            field=models.AutoField(default=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
