# Generated by Django 4.1 on 2024-01-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_remove_book_id_book_book_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="author",
            name="id",
        ),
        migrations.RemoveField(
            model_name="book",
            name="book_number",
        ),
        migrations.AddField(
            model_name="author",
            name="author_id",
            field=models.AutoField(default=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="book_id",
            field=models.AutoField(default=100, primary_key=True, serialize=False),
        ),
    ]
