# Generated by Django 4.1 on 2024-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_rename_name_book_title_remove_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
