# Generated by Django 4.1 on 2024-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_book_id_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.IntegerField(),
        ),
    ]
