# Generated by Django 4.1 on 2024-02-01 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_remove_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
